<div>Редактирование <?= htmlspecialchars($user['name']) ?> (<?= htmlspecialchars($user['id']) ?>)</div>
<form action="/users/<?= htmlspecialchars($user['id']) ?>" method="post">
  <input type="hidden" name="_METHOD" value="PATCH">
  <?php if (isset($errors['common'])): ?>
    <div><?= $errors['common'] ?></div>
  <?php endif ?>
  <div>
    <label>
        Имя
      <input type="text" name="user[name]" value="<?= htmlspecialchars($user['name']) ?>" required>
    </label>
    <?php if (isset($errors['name'])): ?>
      <div><?= $errors['name'] ?></div>
    <?php endif ?>
  </div>
  <div>
    <label>
        Email
      <input type="email" name="user[email]" value="<?= htmlspecialchars($user['email']) ?>" required>
    </label>
    <?php if (isset($errors['email'])): ?>
      <div><?= $errors['email'] ?></div>
    <?php endif ?>
  </div>
  <input type="submit" value="Edit">
</form>